name: Just Nextjs CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }} 
          port: 22
          script: |
            ulimit -u 4096
            ulimit -n 4096
            cd /home/edwardja/repositories/just-nextjs
            git pull origin master
            git status
            npm install
            npm run build
